---
tables:
- name: feature__easyL4FirewallBlacklist
  columnNames:
  - CIDRRange
  rows: []
- name: feature__easyL4FirewallSourceList
  columnNames:
  - CIDRRange
  rows:
  - row:
    - 0.0.0.0/0
- name: monitor__Monitors
  columnNames:
  - Index
  - Name
  - Type
  - Options
  rows:
  - row:
    - '0'
    - "/Common/http"
    - none
    - none
#- name: pool__Members
#  columnNames:
#  - Index
#  - IPAddress
#  - Port
#  - ConnectionLimit
#  - Ratio
#  - PriorityGroup
#  - State
#  - AdvOptions
#  rows:
#  - row:
#    - '0'
#    - "2.2.2.2"
#    - '443'
#    - '0'
#    - '1'
#    - '0'
#    - enabled
#    - none
- name: pool__Pools
  columnNames:
  - Index
  - Name
  - Description
  - LbMethod
  - Monitor
  - AdvOptions
  rows:
  - row:
    - '0'
    - "{{sd_iApp_service_name}}_pool"
    - ''
    - round-robin
    - '0'
    - none
#- name: l7policy__rulesAction
#  columnNames:
#  - Group
#  - Target
#  - Parameter
#  rows:
#  - row:
#    - default
#    - asm/request/enable/policy
#    - bundled:remote_asm1
#- name: l7policy__rulesMatch
#  columnNames:
#  - Group
#  - Operand
#  - Negate
#  - Condition
#  - Value
#  - CaseSensitive
#  - Missing
#  rows:
#  - row:
#    - default
#    - ''
#    - 'no'
#    - ''
#    - ''
#    - 'no'
#    - 'no'
- name: vs__Listeners
  columnNames:
  - Listener
  - Destination
  rows: []
variables:
- name: extensions__Field1
  value: ''
  encrypted: 'no'
- name: extensions__Field2
  value: ''
  encrypted: 'no'
- name: extensions__Field3
  value: ''
  encrypted: 'no'
- name: feature__easyL4Firewall
  encrypted: 'no'
  value: auto
- name: feature__insertXForwardedFor
  encrypted: 'no'
  value: disabled
- name: feature__redirectToHTTPS
  encrypted: 'no'
  value: false
- name: feature__securityEnableHSTS
  encrypted: 'no'
  value: disabled
- name: feature__sslEasyCipher
  encrypted: 'no'
  value: disabled
- name: feature__statsHTTP
  encrypted: 'no'
  value: auto
- name: feature__statsTLS
  encrypted: 'no'
  value: auto
- name: iapp__apmDeployMode
  encrypted: 'no'
  value: preserve-bypass
- name: iapp__appStats
  encrypted: 'no'
  value: enabled
- name: iapp__asmDeployMode
  encrypted: 'no'
  value: preserve-bypass
- name: iapp__logLevel
  encrypted: 'no'
  value: '7'
- name: iapp__mode
  encrypted: 'no'
  value: auto
- name: iapp__routeDomain
  encrypted: 'no'
  value: auto
- name: iapp__strictUpdates
  encrypted: 'no'
  value: disabled
- name: l7policy__defaultASM
  encrypted: 'no'
  value: bypass
- name: l7policy__defaultL7DOS
  encrypted: 'no'
  value: bypass
- name: l7policy__strategy
  encrypted: 'no'
  value: "/Common/first-match"
- name: pool__DefaultPoolIndex
  encrypted: 'no'
  value: '0'
- name: pool__MemberDefaultPort
  value: ''
  encrypted: 'no'
- name: pool__addr
  encrypted: 'no'
  value: "{{ vs_address }}"
- name: pool__mask
  encrypted: 'no'
  value: "{{ vs_mask }}"
- name: pool__port
  encrypted: 'no'
  value: "{{ vs_port }}"
- name: vs__AdvOptions
  value: 'translate-address=enabled'
  encrypted: 'no'
- name: vs__AdvPolicies
  value: '/Common/App1_ltm_policy'
  encrypted: 'no'
- name: vs__AdvProfiles
  value: websecurity
  encrypted: 'no'
- name: vs__ConnectionLimit
  encrypted: 'no'
  value: '0'
- name: vs__Description
  value: ''
  encrypted: 'no'
- name: vs__IpProtocol
  encrypted: 'no'
  value: tcp
- name: vs__Irules
  value: "{{ canary_security_deployments_irule }}"
  encrypted: 'no'
- name: vs__Name
  encrypted: 'no'
  value: ''
- name: vs__OptionConnectionMirroring
  encrypted: 'no'
  value: disabled
- name: vs__OptionSourcePort
  encrypted: 'no'
  value: preserve
- name: vs__ProfileAccess
  value: ''
  encrypted: 'no'
- name: vs__ProfileAnalytics
  value: '/Common/rs_avr_profile'
  encrypted: 'no'
- name: vs__ProfileClientProtocol
  encrypted: 'no'
  value: "/Common/tcp"
- name: vs__ProfileClientSSL
  value: "/Common/clientssl"
  encrypted: 'no'
- name: vs__ProfileClientSSLAdvOptions
  value: ''
  encrypted: 'no'
- name: vs__ProfileClientSSLCert
  value: ''
  encrypted: 'no'
- name: vs__ProfileClientSSLChain
  value: ''
  encrypted: 'no'
- name: vs__ProfileClientSSLCipherString
  encrypted: 'no'
  value: DEFAULT
- name: vs__ProfileClientSSLKey
  value: ''
  encrypted: 'no'
- name: vs__ProfileCompression
  value: ''
  encrypted: 'no'
- name: vs__ProfileConnectivity
  value: ''
  encrypted: 'no'
- name: vs__ProfileDefaultPersist
  value: ''
  encrypted: 'no'
- name: vs__ProfileFallbackPersist
  value: ''
  encrypted: 'no'
- name: vs__ProfileHTTP
  value: "/Common/rs_http_profile"
  encrypted: 'no'
- name: vs__ProfileOneConnect
  value: ''
  encrypted: 'no'
- name: vs__ProfilePerRequest
  value: ''
  encrypted: 'no'
- name: vs__ProfileRequestLogging
  value: ''
  encrypted: 'no'
- name: vs__ProfileSecurityDoS
  value: '/Common/rs_dosl7_profile'
  encrypted: 'no'
- name: vs__ProfileSecurityLogProfiles
  value: "rs_asm_log_to_splunk , 'rs_log_all_local'"
  encrypted: 'no'
- name: vs__ProfileServerProtocol
  value: ''
  encrypted: 'no'
- name: vs__ProfileServerSSL
  value: 'none'
  encrypted: 'no'
- name: vs__RouteAdv
  encrypted: 'no'
  value: disabled
- name: vs__SNATConfig
  encrypted: 'no'
  value: automap
- name: vs__SourceAddress
  encrypted: 'no'
  value: 0.0.0.0/0
- name: vs__VirtualAddrAdvOptions
  value: ''
  encrypted: 'no'
