---


#configure module wide defaults, don't configure any of the CFT/app specifc defaults. 
# CFT/app specifc defaults should be configured in the template file.


# CFT / iapp global parameters
service: "www.demo.f5example.com"
service_name: "www_demo_f5example_com"
partition: "Common"
strict_updates: false
validate_certs: false
dosl7_profile_name: "rs_dosl7_profile"
proactive_autometed_attack_prevention: "disabled"
vs_address: "0.0.0.0"
vs_mask: "255.255.255.255"
vs_port: "443"
partition: "Common"
as3_template_name: as3_https_basic_w_waf
fps_profile_name: "rs_fps_profile"
login_password_encryption: "disabled"
login_page_file: "login"
login_page_path: "user"
dosl7_whitelist_ip: "12.12.12.12/32"


#######AS3 serivce definition#########
as3_http_basic_name: "as3_app1"
as3_http_virtual_address: "4.4.4.4"
as3_http_pool_name: "as3_pool1"
as3_service_label: "app1"

###Canary deployment
waf_policy_name_canary: "main_asm_policy"
dosl7_profile_name_canary: "main_dosl7_policy"
canary_security_deployments_irule: "/Common/canary_security_deployments"



## SSL CERT 
#client_ssl_cert_name: "{{ service_name }}"
client_ssl_cert_name: "default"

ltm_policy_name: "{{ service_name }}_ltm_policy" 
waf_policy_name: "linux-high"
asm_policy_base64: "{{ lookup('file', 'asm-policy-' + waf_policy_name + '.xml') | b64encode }}"

logging_profile_name: "asm_log_to_splunk"
analytics_profile_name: "my_analytics_profile"



# Internal varaiables (used to build the module)
sd_iApp_service_name: "{{ service_name }}_sd"
sd_jinja_template_name: "{{ sd_iApp_template_name + '.j2' }}"
sd_iApp_template_name: "f5.service_discovery"


as3_template_file_name: "{{ as3_template_name + '.j2'}}"
as3_declaration_file_name: "{{ as3_template_name + '_' + service_name + '.json'}}"
as3_parameters_file_name: "{{ as3_template_name + '_parameters.yaml'}}"


# Pool Name ex.
# /Common/www_demo_f5example_com_service_discovery.app/www_demo_f5example_com_service_discovery_pool
application_pool_name: "/{{partition}}/{{sd_iApp_service_name}}.app/{{sd_iApp_service_name}}_pool"


# iApp Specific variables
iApp_service_name: "{{ service_name }}"
# TEMPLATE NAME:
iApp_template_name: "appsvcs_v2.0.004"
# TEMPLATE TYPE
iApp_template_type: "https_vip_w_waf"
# iApp_template_type: "https_vip_w_waf"
#jinja_template_name: "{{ iApp_template_type + '_' + iApp_template_name + '.j2' }}"
bigip_mgmt_port: 8443


# Pool Vars
applicationPoolTagKey: "aws:autoscaling:groupName"
applicationPoolTagValue: "doesntwork"





