---

#pulls an asm policy from a bigip and saves it locally in the repo
# taken from https://github.com/fchmainy/secDevops/blob/master/exportPolicy.yaml 


- name: get ID
  f5_asm_getPolicyID:
      server: "{{ bigip_ip_addr }}"
      user: "{{ vault_bigip_rest_user }}"
      password: "{{ vault_bigip_rest_password }}"
      policyName: "{{ asm_policy_name }}"
      validate_certs: "{{ validate_certs }}"
  register: policyId

- name: EXPORT POLICY
  f5_asm_exportPolicy:
      server: "{{ bigip_ip_addr }}"
      serviceName: "{{ asm_policy_name }}"
      policyId: "{{policyId.policyId}}"
      user: "{{ vault_bigip_rest_user }}"
      password: "{{ vault_bigip_rest_password }}"
      validate_certs: "{{ validate_certs }}"
  delegate_to: localhost
  register: taskId


- name: GET STATUS OF THE EXPORT
  f5_asm_getStatus:
      server: "{{ bigip_ip_addr }}"
      taskId: "{{taskId.exportTask}}"
      taskType: "export-policy"
      user: "{{ vault_bigip_rest_user }}"
      password: "{{ vault_bigip_rest_password }}"
      validate_certs: "{{ validate_certs }}"
  delegate_to: localhost
  register: myStatus
  until: myStatus.taskStatus | default("COMPLETED")== "COMPLETED"
  retries: 10
  delay: 5

- name: GET EXPORTED POLICY
  f5_asm_getExportedPolicy:
      server: "{{ bigip_ip_addr }}"
      serviceName: "{{ asm_policy_name }}"
      user: "{{ vault_bigip_rest_user }}"
      password: "{{ vault_bigip_rest_password }}"
      validate_certs: "{{ validate_certs }}"
      policy_new_name: "{{ policy_new_name }}"
  delegate_to: localhost
  register: result