---
### DEPLOY AN VIRTUAL SERVICE FROM AN IAPP IN ANSIBLE

- hosts: localhost
  connection: local
  gather_facts: False
  vars:
     state: "{{ rs_state | default('present')}}"    
  vars_files:
  - /home/snops/f5-rs-global-vars-vault.yaml  
  environment:
      F5_SERVER: "{{ bigip_ip_addr }}"
      F5_USER: "{{ vault_bigip_rest_user }}"
      F5_PASSWORD: "{{ vault_bigip_rest_password }}"  #Inherit from vault
      F5_SERVER_PORT: "{{ bigip_mgmt_port }}"
      F5_VALIDATE_CERTS: "{{ validate_certs }}"
  roles:
    - waf_policies